# Generated by Django 3.1.2 on 2020-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='imageUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
